runtime: nodejs18  # 使用するNode.jsのバージョンを指定

handlers:
- url: /(.*\.(gif|png|jpg|css|js|ico|json|txt|svg|woff|ttf|eot))$
  static_files: dist/myapp/\1
  upload: dist/myapp/(.*\.(gif|png|jpg|css|js|ico|json|txt|svg|woff|ttf|eot))$
  secure: always

- url: .*
  static_files: dist/myapp/index.html
  upload: dist/myapp/index.html
  secure: always
